
S = /
EXTSHARED = .so
EXTEXECUTABLE = 

PLATFORMSPECIFICFLAGS = -fPIC

PLATFORMSPECIFICLIBS = -lopenal -lvorbisenc -lvorbisfile -lvorbis -lfreetype -lBulletDynamics -lBulletCollision -lLinearMath
PLATFORMSPECIFICSHAREDOBJECTS =  
DIRLIBS =
DIRINCLUDEPC = -I/usr/include -I/usr/include/irrlich -I/usr/include/bullet

DEPENDENCIES =  $(PLATFORMSPECIFICSHAREDOBJECTS)

MD = mkdir
CP = cp -r
RM = rm -f
